### ISSUE TITLE
Raspberry Script

### ISSUE THREAD

**Issue by StanBarrows** [StanBarrows/raspberry-adscreens#15]
Heyho:

- [x] Kannst du noch in die Anleitung aufnehmen wie und wo ich das .env Files erstellen muss + Welche Variabeln ? Am besten ein .env.example in das repo kopieren.

- [x] Wenn ich die libraries im requirements.txt über pip install versuche zu installieren erhalte ich bei pyaml-env ein Fehler

```
  Could not find a version that satisfies the requirement pyaml-env (from versions: )
No matching distribution found for pyaml-env
```

- [x] Wenn ich das Script aktuell auf dem Raspberry ausführe erhalte ich ein SyntaxError:

```
  File "autostart.py", line 66
    print(f"STATUS CODE: {status_code} URL {resposne_url}")
                                                         ^
SyntaxError: invalid syntax
```

Nicht sicher ob ich print auch noch installieren muss? habe es jetzt einmal auskommentiert.

- [x] Nach der auskommentierten stelle kommt als nächstes der nachfolgende Fehler. Kannst du mal schauen welche libraries ich exakt installieren muss und das in das requirements.txt aufnehmen?

```
Traceback (most recent call last):
  File "pyautostart/autostart/autostart.py", line 8, in <module>
    from config.gtconf import CONFIG
ImportError: No module named config.gtconf
```

- [x] Hab die Response Values Angepasst.

```
    Expected Server Responses:
        200: OK will return json respone with url to display page.
        401: Unauthenticated - Wrong AUTH
        422: Invalid Request Body Parameters
        403: No Display was assigned to the Device. (Add Display via Backend)
        403: Trashed Display


```

- [x] Ich habe die URLS & IF Else so reduziert wie es aktuell passen sollte, der neuste Code ist im Main Branch

**Comment by StanBarrows** [comment]
Sieht gut aus! Vielen Dank.
